/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InstallationAbortedView.java
 *
 * Created on 04-oct-2010, 15:38:50
 */
package ingenias.installergenerator.view;

import ingenias.installergenerator.control.BasicEvent;
import ingenias.installergenerator.control.Controller;
import ingenias.installergenerator.control.EventId;

/**
 *
 * @author Carlos
 */
public class InstallationAbortedView extends javax.swing.JPanel implements WizardEventListener {

    /** Creates new form InstallationAbortedView */
    public InstallationAbortedView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reasonsArea = new javax.swing.JTextArea();

        jLabel1.setText("The Installation was aborted for the following reasons:");

        reasonsArea.setColumns(20);
        reasonsArea.setRows(5);
        jScrollPane1.setViewportView(reasonsArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea reasonsArea;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the reasonsArea
     */
    public javax.swing.JTextArea getReasonsArea() {
        return reasonsArea;
    }

    public void next() {
        Controller.getController().event(new BasicEvent(EventId.Next));
    }

    public void back() {
    }

    public void cancel() {
    }
}
