/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IzPackAntPathFormView.java
 *
 * Created on 13-oct-2010, 16:39:32
 */

package ingenias.installergenerator.view;

import ingenias.installergenerator.control.BasicEvent;
import ingenias.installergenerator.control.Controller;
import ingenias.installergenerator.control.EventId;
import ingenias.installergenerator.control.PathsEvent;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 *
 * @author Carlos
 */
public class IzPackAntPathFormView extends javax.swing.JPanel implements WizardEventListener{

    /** Creates new form IzPackAntPathFormView */
    public IzPackAntPathFormView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        izPackTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        izPackButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        antTextField = new javax.swing.JTextField();
        antButton = new javax.swing.JButton();

        izPackTextField.setText("C:\\Program Files\\IzPack");

        jLabel1.setText("Please, indicate the installation path of the following programs:");

        jLabel2.setText("IzPack install directory:");

        izPackButton.setText("...");
        izPackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izPackButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Apache Ant install directory:");

        antTextField.setText("C:\\Program Files\\Ant");

        antButton.setText("...");
        antButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(antTextField)
                            .addComponent(izPackTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(antButton, 0, 0, Short.MAX_VALUE)
                            .addComponent(izPackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(izPackTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izPackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(antTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(antButton))
                .addContainerGap(200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void izPackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izPackButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int returnVal = chooser.showDialog(this, "Select Directory");
        if(returnVal==JFileChooser.APPROVE_OPTION){
            String path="";
            try {
                path = chooser.getSelectedFile().getCanonicalPath();
            } catch (IOException ex) {
                path = chooser.getSelectedFile().getAbsolutePath();
            }

            this.izPackTextField.setText(path);
        }

    }//GEN-LAST:event_izPackButtonActionPerformed

    private void antButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int returnVal = chooser.showDialog(this, "Select Directory");
        if(returnVal==JFileChooser.APPROVE_OPTION){
            String path="";
            try {
                path = chooser.getSelectedFile().getCanonicalPath();
            } catch (IOException ex) {
                path = chooser.getSelectedFile().getAbsolutePath();
            }

            this.antTextField.setText(path);
        }
    }//GEN-LAST:event_antButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton antButton;
    private javax.swing.JTextField antTextField;
    private javax.swing.JButton izPackButton;
    private javax.swing.JTextField izPackTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public void next() {
        PathsEvent event = new PathsEvent();
        event.setAntInstallDir(new File(antTextField.getText()));
        event.setIzPackInstallDir(new File(izPackTextField.getText()));

        event.setId(EventId.Next);

        Controller.getController().event(event);
    }

    public void back() {

    }

    public void cancel() {
       Controller.getController()
                .event(new BasicEvent(EventId.Cancel));
    }

}
