/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VerifyingAntIzPackView.java
 *
 * Created on 04-oct-2010, 12:15:45
 */

package ingenias.installergenerator.view;

import javax.swing.JPanel;

/**
 *
 * @author Carlos
 */
public class LabelledProcessView extends javax.swing.JPanel  implements WizardEventListener{

    /** Creates new form VerifyingAntIzPackView */
    public LabelledProcessView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();

        label.setText("Verifying Required Programs...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(label)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the label
     */
    public javax.swing.JLabel getLabel() {
        return label;
    }

    public void next() {
    }

    public void back() {
    }

    public void cancel() {
    }


}
