/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RequestSelectDeploymentView.java
 *
 * Created on 04-oct-2010, 15:20:11
 */
package ingenias.installergenerator.view;

import ingenias.installergenerator.control.BasicEvent;
import ingenias.installergenerator.control.Controller;
import ingenias.installergenerator.control.EventId;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author Carlos
 */
public class RequestSelectDeploymentView extends javax.swing.JPanel implements WizardEventListener {

    /** Creates new form RequestSelectDeploymentView */
    public RequestSelectDeploymentView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelButtons = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();

        jLabel1.setText("Please select one or more Deployment Packages to generate Installers:");

        panelButtons.setLayout(new javax.swing.BoxLayout(panelButtons, javax.swing.BoxLayout.Y_AXIS));

        jCheckBox1.setText("jCheckBox1");
        panelButtons.add(jCheckBox1);

        jCheckBox2.setText("jCheckBox2");
        panelButtons.add(jCheckBox2);

        jCheckBox3.setText("jCheckBox3");
        panelButtons.add(jCheckBox3);

        jCheckBox4.setText("jCheckBox4");
        panelButtons.add(jCheckBox4);

        jScrollPane1.setViewportView(panelButtons);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelButtons;
    // End of variables declaration//GEN-END:variables
    private List<String> deployments = null;

    /**
     * @return the deployments
     */
    public List<String> getDeployments() {
        return deployments;
    }

    /**
     * @param deployments the deployments to set
     */
    public void setDeployments(List<String> deployments) {
        this.deployments = deployments;
        this.panelButtons.removeAll();
        for (String deployment : deployments) {
            JCheckBox checkBox = new JCheckBox(deployment);
            checkBox.setSelected(true);
            this.panelButtons.add(checkBox);
        }
        this.panelButtons.updateUI();
    }

    public void next() {
        ArrayList<String> selectedDeployments = new ArrayList<String>();
        for (Component comp : this.panelButtons.getComponents()) {
            JCheckBox checkBox = (JCheckBox) comp;
            if (checkBox.isSelected()) {
                selectedDeployments.add(checkBox.getText());
            }
        }
        Controller.getController()
                .event(new BasicEvent(EventId.DeploymentsToGenerateInstaller,
                selectedDeployments));
    }

    public void back() {
    }

    public void cancel() {
        Controller.getController()
                .event(new BasicEvent(EventId.Cancel));
    }
}
