/*
    Copyright (C) 2002 Jorge Gomez Sanz

    This file is part of INGENIAS IDE, a support tool for the INGENIAS
    methodology, availabe at http://grasia.fdi.ucm.es/ingenias or
    http://ingenias.sourceforge.net

    INGENIAS IDE is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    INGENIAS IDE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with INGENIAS IDE; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*/

package ingenias.generator.browser;

import java.util.Iterator;

// It represents a relationship in a diagram. It can contain attributes.
public interface GraphRelationship extends AttributedElement {

   // Obtains the type of the relationship
   public String getType();

   // Obtains the extremes of the relationship
   public GraphRole[] getRoles();
   
   // Obtains the graph which this relationship belongs to
   public Graph getGraph();
   
   // Obtains the id of this relationship. This ID is autogenerated 
   // by the environment and cannot be modified by users,so it 
   // is not user friendly
   public String getID();

}